USE TENNIS;

CREATE TABLE PARTICIPANTS(
ID_EPREUVE BIGINT NOT NULL,
ID_JOUEUR BIGINT NOT NULL,
PRIMARY KEY(ID_EPREUVE, ID_JOUEUR),
FOREIGN KEY(ID_JOUEUR) REFERENCES JOUEUR(ID),
FOREIGN KEY(ID_EPREUVE) REFERENCES EPREUVE(ID)
) ENGINE=InnoDB;
